name       : pocillo-gtk-theme
version    : 0.7
release    : 1
source     :
    - https://github.com/UbuntuBudgie/pocillo-gtk-theme/archive/v0.7.tar.gz : 00be4578eae463db2f9510e3bcf9f4ebae59120debbca54a529b54ae47f3bcb2
homepage   : https://github.com/UbuntuBudgie/pocillo-gtk-theme
license    :
    - CC-BY-SA-4.0
    - GPL-2.0-or-later
component  : desktop.theme
summary    : Material Design GTK Theme
description: |
     GTK based theme for the Budgie Desktop that has Material Design elements and styled using the Arc colour palette.
builddeps  :
    - inkscape
    - optipng
    - sassc
rundeps    :
    - gtk-engines
    - gtk2-engine-murrine
setup      : |
    sed -i 's|@extend %frame_flat|@extend %frame_flat !optional|g' src/gtk-3.0/3.22/sass/widgets/_frame.scss
build      : |
    %make
install    : |
    %make_install

    #Fix broken symbolic links for gkt-3.0
    for themes in Pocillo Pocillo-dark Pocillo-dark-slim Pocillo-light Pocillo-light-slim Pocillo-slim ; do
        rm $installdir/usr/share/themes/${themes}/gtk-3.0
        ln -sv /usr/share/themes/${themes}/gtk-3.22 $installdir/usr/share/themes/${themes}/gtk-3.0
    done
