name       : pocillo-gtk-theme
version    : 0.8
release    : 2
source     :
    - https://github.com/UbuntuBudgie/pocillo-gtk-theme/archive/refs/tags/v0.8.tar.gz : 61358cd862e7356367bc5b9fcdcc0f153301f7c4c4887a7b8f3994506bf2ff00
homepage   : https://github.com/UbuntuBudgie/pocillo-gtk-theme
license    : GPL-2.0-or-later
component  : desktop.theme
summary    : Material Design GTK Theme
description: |
    GTK based theme for the Budgie Desktop that has Material Design elements and styled using the Arc colour palette.
networking : yes
builddeps  :
    - pkgconfig(gtk4)
    - sassc
    - nodejs
rundeps    :
    - gtk-engines
    - gtk2-engine-murrine
setup      : |
    %meson_configure -Dtheme_name=Pocillo
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share/themes/*/{COPYING,INSTALL_GDM_THEME.md}
