name       : pocillo-gtk-theme
version    : '0.9'
release    : 3
source     :
    - https://github.com/UbuntuBudgie/pocillo-gtk-theme/archive/refs/tags/v0.9.tar.gz : 7bbb7fb7d12107b4d6387368839cd337587b6293b74e119e2a4e26ce4b8d67d0
homepage   : https://github.com/UbuntuBudgie/pocillo-gtk-theme
license    : GPL-2.0-or-later
component  : desktop.theme
summary    : Material Design GTK Theme
description: |
    GTK based theme for the Budgie Desktop that has Material Design elements and styled using the Arc colour palette.
networking : yes
builddeps  :
    - pkgconfig(gtk4)
    - sassc
    - nodejs
rundeps    :
    - gtk-engines
    - gtk2-engine-murrine
setup      : |
    %meson_configure -Dtheme_name=Pocillo
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share/themes/*/{COPYING,INSTALL_GDM_THEME.md}
