name       : python-pikepdf
version    : 1.10.3
release    : 6
source     :
    - https://github.com/pikepdf/pikepdf/archive/v1.10.3.tar.gz : 972a5a08db97f920cb8ba2a1cfafd08d31a01bd248d3d9e308687c5fe16ebbe2
homepage   : https://pikepdf.readthedocs.io/
license    : MPL-2.0
component  : programming.python
summary    : A Python library for reading and writing PDF, powered by qpdf
description: |
    Pikepdf is a Python library for reading and writing PDF files.
builddeps  :
    - pkgconfig(libqpdf)
    - pkgconfig(python3)
    - pybind11
    - python-setuptools
    - python-setuptools-scm-git-archive # Not in Repo
rundeps    :
    - python-lxml
build      : |
    %python3_setup
install    : |
    %python3_install
