name       : python-pikepdf
version    : 1.10.4
release    : 7
source     :
    - https://github.com/pikepdf/pikepdf/archive/v1.10.4.tar.gz : 7fe647aecd4495bad5099a66fd5c983befc1a2a14812a1014294559634f512ef
homepage   : https://pikepdf.readthedocs.io/
license    : MPL-2.0
component  : programming.python
summary    : A Python library for reading and writing PDF, powered by qpdf
description: |
    Pikepdf is a Python library for reading and writing PDF files.
builddeps  :
    - pkgconfig(libqpdf)
    - pkgconfig(python3)
    - pybind11
    - python-setuptools
    - python-setuptools-scm-git-archive # Not in Repo
rundeps    :
    - python-lxml
build      : |
    %python3_setup
install    : |
    %python3_install
