name       : python-rx
version    : 3.1.0
release    : 3
source     :
    - https://github.com/ReactiveX/RxPY/archive/v3.1.0.tar.gz : 88b31fe8cc070b0c22e3f53c22d9c82994be36cced95d9cf1f207487c4388c3c
homepage   : https://rxpy.rtfd.io
license    : MIT
component  : programming.python
summary    : Reactive extensions for Python
description: |
    A library for composing asynchronous and event-based programs using observable collections and query operator functions in Python
builddeps  :
    - pytest-asyncio	# Check but not yet in Repo
    - pytest-runner
    - python-coverage
rundeps    :
     - pytest-asyncio
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
