name       : bauh
version    : 0.10.0
release    : 3
source     :
    - https://github.com/vinifmor/bauh/archive/refs/tags/0.10.0.tar.gz : ffa578238522b1774db4359406c79f0e54ce19d3eb1ce8bc04163fc23d823aa5
homepage   : https://github.com/vinifmor/bauh
license    : Zlib
component  : desktop
summary    : Graphical interface for application management (AppImage, Flatpak, Snap, Web)
description: |
    bauh (ba-oo), formerly known as fpakman, is a graphical interface for managing your Linux software (packages/applications). It currently supports the following formats: AppImage, Flatpak, Snap and Web applications.
builddeps  :
    - flatpak           # check
    - python-colorama   # check
    - python-dateutil   # check
    - python-packaging  # check
    - python-requests   # check
    - python3-qt5       # check
rundeps    :
    - aria2
    - flatpak
    - python-colorama
    - python-dateutil
    - python-packaging
    - python-requests
    - python3-qt5
    - snapd
    - wget
build      : |
    %python3_setup
install    : |
    %python3_install
    install -Dm00644 bauh/desktop/*.desktop -t $installdir/usr/share/applications
check      : |
    %python3_test
