name       : colloid-icon-theme
version    : 2023.03.28
release    : 1
source     :
    - https://github.com/vinceliuice/Colloid-icon-theme/archive/refs/tags/2023-03-28.tar.gz : edaffdbfbcd5729ff5c3b1c1b3c68da04b12dde8026e2eceada32f8f46e50962
homepage   : https://github.com/vinceliuice/Colloid-icon-theme
license    : GPL-3.0-or-later
component  : desktop.theme
summary    : Colloid icon theme for linux desktops
description: |
    Colloid icon theme for linux desktops
rundeps    :
    - gtk-engines
    - gtk2-engine-murrine
setup      : |
    sed -e '/gtk-update-icon-cache/d' -i install.sh
install    : |
    install -dm00644 $installdir/usr/share/icons
    ./install.sh --dest $installdir/usr/share/icons
