name       : gti
version    : 1.9.1
release    : 2
source     :
    - https://github.com/rwos/gti/archive/refs/tags/v1.9.1.tar.gz : f8a3afdd3967fe7d88bd1b0b9f5cb62ae04dc9ba458238da91efc213f61a9cf9
homepage   : https://r-wos.org/hacks/gti
license    : MIT
component  : programming.tools
summary    : Just a silly git launcher, basically
description: |
    Just a silly git launcher, basically. Inspired by sl.
build      : |
    %make
install    : |
    %make_install
