name       : python-humanfriendly
version    : '9.1'
release    : 2
source     :
    - https://github.com/xolox/python-humanfriendly/archive/9.1.tar.gz : b603d8abeca579e7a69e969da68c9b818f04da0b2ec5cfb18a031da385f43f44
homepage   : https://humanfriendly.readthedocs.org
license    : MIT
component  : programming.python
summary    : Human friendly input/output for text interfaces using Python
description: |
    Human friendly input/output in Python. The functions and classes in the humanfriendly package can be used to make text interfaces more user friendly.
builddeps  :
    - python-capturer    # Extra Repo
    - python-coloredlogs # Extra Repo
    - python-docutils
    - python-mock
rundeps    :
    - python-docutils
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
