name       : pcmanfm
version    : 1.3.2
release    : 1
source     :
    - https://downloads.sourceforge.net/pcmanfm/pcmanfm-1.3.2.tar.xz : 14cb7b247493c4cce65fbb5902611e3ad00a7a870fbc1e50adc50428c5140cf7
homepage   : https://lxde.org/
license    : GPL-2.0-or-later
component  : desktop.lxde
summary    : The file manager for LXDE
description: |
    Extremely fast and lightweight file manager for LXDE.
builddeps  :
    - pkgconfig(x11)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(libfm)
    - pkgconfig(libfm-extra)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
