name       : timeshift
version    : 22.11.2
release    : 4
source     :
    - https://github.com/linuxmint/timeshift/archive/refs/tags/22.11.2.tar.gz : 36fd19865d1d30dc5f6eca468ceaa3dad01cd95d9090d050d67f5c2cd98fe37d
homepage   : https://github.com/linuxmint/timeshift
license    : LGPL-3.0-or-later
component  : system.utils
summary    : System restore tool for Linux.
description: |
    System restore tool for Linux. Creates filesystem snapshots using rsync+hardlinks, or BTRFS snapshots. Supports scheduled snapshots, multiple backup levels, and exclude filters. Snapshots can be restored while system is running or from Live CD/USB.
builddeps  :
    - pkgconfig(gee-0.8)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(vte-2.91)
    - vala
rundeps    :
    - rsync
setup      : |
    %patch -p1 < $pkgfiles/Add-systemd-times-units.patch

    # remove forced dependency on crontab/cronie
    sed -i '/dependencies/s:"crontab",::' src/Core/Main.vala
    sed -i 's:--thread:& Core/AppExcludeEntry.vala:' src/makefile
build      : |
    %make
install    : |
    %make_install

    # install systemd timers
    install -Dm00644 files/timeshift.{service,timer} -t $installdir/%libdir%/systemd/system

    # Enable timeshift timers by default
    install -dm00755 $installdir/%libdir%/systemd/system/timers.target.wants
    ln -sv %libdir%/systemd/system/timeshift.timer $installdir/%libdir%/systemd/system/timers.target.wants/timeshift.timer
