name       : colloid-icon-theme
version    : 2023.07.01
release    : 2
source     :
    - https://github.com/vinceliuice/Colloid-icon-theme/archive/refs/tags/2023-07-01.tar.gz : e97d525b843e504cf652d21738d699b1e69833a915dabd30ae897f42f6de3e47
homepage   : https://github.com/vinceliuice/Colloid-icon-theme
license    : GPL-3.0-or-later
component  : desktop.theme
summary    : Colloid icon theme for linux desktops
description: |
    Colloid icon theme for linux desktops
rundeps    :
    - gtk-engines
    - gtk2-engine-murrine
setup      : |
    sed -e '/gtk-update-icon-cache/d' -i install.sh
install    : |
    install -dm00644 $installdir/usr/share/icons
    ./install.sh --dest $installdir/usr/share/icons
