name       : colloid-icon-theme
version    : 2025.02.09
release    : 3
source     :
    - https://github.com/vinceliuice/Colloid-icon-theme/archive/refs/tags/2025-02-09.tar.gz : 8b4f2e577768c9c40c5f9a634eb9f08172c4574ea19f2fcc39177b819524b4a9
homepage   : https://github.com/vinceliuice/Colloid-icon-theme
license    : GPL-3.0-or-later
component  : desktop.theme
summary    : Colloid icon theme for linux desktops
description: |
    Colloid icon theme for linux desktops
rundeps    :
    - gtk-engines
    - gtk2-engine-murrine
setup      : |
    sed -e '/gtk-update-icon-cache/d' -i install.sh
install    : |
    install -dm00644 $installdir/usr/share/icons
    ./install.sh --dest $installdir/usr/share/icons
