name       : numlockx
version    : 1.2
release    : 1
source     :
    - https://github.com/rg3/numlockx/archive/1.2.tar.gz : 9affd0687ecd3d942d012bf6bda4311ded22011119f0d13ebf5d3a8544e8047c
license    : MIT
component  : xorg.apps
summary    : Turns on the numlock key in X11
description: |
    Turns on the numlock key in X11
builddeps  :
    - pkgconfig(xtst)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
