name       : timeshift
version    : 22.06.1
release    : 2
source     :
    - https://github.com/teejee2008/timeshift/archive/refs/tags/v22.06.1.tar.gz : aef3980c19dfde9084b47b4e04e5106489ee7ddf44e6228415d2521405a091ec
homepage   : https://github.com/teejee2008/timeshift
license    : LGPL-3.0-or-later
component  : system.utils
summary    : System restore tool for Linux.
description: |
    System restore tool for Linux. Creates filesystem snapshots using rsync+hardlinks, or BTRFS snapshots. Supports scheduled snapshots, multiple backup levels, and exclude filters. Snapshots can be restored while system is running or from Live CD/USB.
builddeps  :
    - pkgconfig(gee-0.8)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(vte-2.91)
    - vala
rundeps    :
    - rsync
setup      : |
    %patch -p1 < $pkgfiles/Add-systemd-times-units.patch

    # remove forced dependency on crontab/cronie
    sed -i '/dependencies/s:"crontab",::' src/Core/Main.vala
    sed -i 's:--thread:& Core/AppExcludeEntry.vala:' src/makefile
build      : |
    %make
install    : |
    %make_install

    # install systemd timers
    install -Dm00644 files/timeshift.{service,timer} -t $installdir/%libdir%/systemd/system
