name       : timeshift
version    : 21.09.1
release    : 1
source     :
    - https://github.com/teejee2008/timeshift/archive/refs/tags/v21.09.1.tar.gz : 70b21355439c284860264f746b980f11614c8e8307106d37f8fbee98377c455d
homepage   : https://github.com/teejee2008/timeshift
license    : LGPL-3.0-or-later
component  : system.utils
summary    : System restore tool for Linux.
description: |
    System restore tool for Linux. Creates filesystem snapshots using rsync+hardlinks, or BTRFS snapshots. Supports scheduled snapshots, multiple backup levels, and exclude filters. Snapshots can be restored while system is running or from Live CD/USB.
builddeps  :
    - pkgconfig(gee-0.8)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(vte-2.91)
    - vala
rundeps    :
    - cronie # Extra Repo
    - rsync
build      : |
    %make
install    : |
    %make_install
