name       : bandwhich
version    : 0.12.0
release    : 2
source     :
    - https://github.com/imsnif/bandwhich/archive/0.12.0.tar.gz : 195693dccff3f5104376c2aa83340583440ac2c40c4f4289fe07b6948ca5d363
homepage   : https://github.com/imsnif/bandwhich
license    : MIT
component  : network.util
summary    : Terminal bandwidth utilization tool
description: |
    This is a CLI utility for displaying current network utilization by process, connection and remote IP/hostname
networking : yes
builddeps  :
    - cargo
    - rust
build      : |
    cargo build %JOBS% --release --locked
install    : |
    install -Dm00755 target/release/bandwhich $installdir/usr/bin/bandwhich
    install -Dm00644 docs/bandwhich.1 $installdir/usr/share/man/man1/bandwhich.1
