name       : procs
version    : 0.14.0
release    : 8
source     :
    - https://github.com/dalance/procs/archive/refs/tags/v0.14.0.tar.gz : fa5af0951dc8aa63c0590f8c5c1136594866057704cfb1cdfc22ac3cc49437c6
homepage   : https://github.com/dalance/procs
license    : MIT
component  : system.utils
summary    : A modern replacement for ps written in Rust
description: |
    procs is a modern replacement for ps written in Rust.
networking : yes
builddeps  :
    - cargo
build      : |
    cargo build --release
    target/release/procs --gen-completion bash
    target/release/procs --gen-completion fish
    target/release/procs --gen-completion zsh
install    : |
    install -Dm00755 target/release/procs -t $installdir/usr/bin/
    install -Dm00644 _procs -t $installdir/usr/share/zsh/site-functions
    install -Dm00644 procs.bash $installdir/usr/share/bash-completion/completions/procs
    install -Dm00644 procs.fish -t $installdir/usr/share/fish/vendor_completions.d
check      : |
    cargo test
