name       : layan-gtk-theme
version    : 2023.05.23
release    : 3
source     :
    - https://github.com/vinceliuice/Layan-gtk-theme/archive/refs/tags/2023-05-23.tar.gz : f6affb35927a0d92bb6f46f45648405d4b57adb6bdb89d68cc529faf3e96b32d
homepage   : https://github.com/vinceliuice/Layan-gtk-theme
license    : GPL-2.0-or-later
component  : desktop.theme
summary    : Layan is a flat Material Design theme
description: |
    Layan is a flat Material Design theme for GTK 3, GTK 2 and Gnome-Shell which supports GTK 3 and GTK 2 based desktop environments like Gnome, Budgie, etc.
rundeps    :
    - gtk-engines
    - gtk2-engine-murrine
install    : |
    install -dm00644 $installdir/usr/share/themes
    ./install.sh --dest $installdir/usr/share/themes
    rm -rf $installdir/usr/share/themes/*/{AUTHORS,COPYING}
