name       : python-dateparser
version    : 1.0.0
release    : 2
source     :
    - https://github.com/scrapinghub/dateparser/archive/v1.0.0.tar.gz : aeaa2025f8b66d32757dfde5b988ce57e3addaaae8d56b99f69c14f6fdf996ee
homepage   : https://github.com/scrapinghub/dateparser
license    : BSD-3-Clause
component  : programming.python
summary    : python parser for human readable dates
description: |
    dateparser provides modules to easily parse localized dates in almost any string formats commonly found on web pages.
builddeps  :
    - python-dateutil
    - python-mock
    - python-parameterized # Not in repo
    - python-regex
    - python-tzlocal
build      : |
    %python3_setup
install    : |
    %python3_install
#check      : |
#    %python3_test # many modules missing.
