name       : tikzit
version    : 2.1.6
release    : 1
source     :
    - https://github.com/tikzit/tikzit/archive/refs/tags/v2.1.6.tar.gz : 40e160f654a25a3a36d6a5361eef71a51f9d3b5eec3b42dd9246ec26402149d1
homepage   : https://tikzit.github.io/
license    : GPL-3.0-or-later
component  : desktop
summary    : pgf/TikZ diagram editor
description: |
    TikZiT is a graphical tool for rapidly creating graphs and string diagrams using PGF/TikZ.
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(poppler-qt5)
setup      : |
    %qmake PREFIX=$installdir/usr
build      : |
    %make
install    : |
    %make_install
