name       : bibata-cursors
version    : 0.4.2
release    : 1
source     :
    - https://github.com/KaizIqbal/Bibata_Cursor/archive/v0.4.2.tar.gz : d00f91ebefa34d5c7d578c78a17825238fcb90540de0dbf4cf3ffb587e1ae976
homepage   : https://github.com/KaizIqbal/Bibata_Cursor
license    : GPL-3.0-or-later
component  : desktop.theme
summary    : Material Based Cursor
description: |
    Bibata is OpenSource, Compact and Material Designed Cursor set. This project masterelop for improve Cursor Experience. This cursor theme pack include four variants: Bibata-Amber, Bibata Classic, Bibata Ice and Bibata Oil.
install    : |
    install -dm00644 $installdir/usr/share/icons
    cp -r Bibata_Amber/out/X11/Bibata_Amber     $installdir/usr/share/icons/Bibata-Amber
    cp -r Bibata_Classic/out/X11/Bibata_Classic $installdir/usr/share/icons/Bibata-Classic
    cp -r Bibata_Ice/out/X11/Bibata_Ice         $installdir/usr/share/icons/Bibata-Ice
    cp -r Bibata_Oil/out/X11/Bibata_Oil         $installdir/usr/share/icons/Bibata-Oil
