name       : we10x-icon-theme
version    : 2020.12.05
release    : 1
source     :
    - git|https://github.com/yeyushengfan258/We10X-icon-theme : 75b5af72ead150170bd1ea3ef4a91e564d03097d
homepage   : https://github.com/yeyushengfan258/We10X-icon-theme
license    : GPL-3.0-or-later
component  : desktop.theme
summary    : A colorful design icon theme for all linux desktops
description: |
    A colorful design icon theme for all linux desktops!
setup      : |
    %patch -p1 < $pkgfiles/0001-fix-install.patch
install    : |
    install -dm00644 $installdir/usr/share/icons
    ./install.sh -d $installdir/usr/share/icons/
    chmod -R 00644 $installdir/usr/share/icons/*
    rm -rf $installdir/usr/share/icons/*/{AUTHORS,COPYING}
