name       : we10x-icon-theme
version    : 2020.06.01
release    : 2
source     :
    - git|https://github.com/yeyushengfan258/We10X-icon-theme : 94b9b85114e8c07e475c0fb5abcc542afe2d2592
homepage   : https://github.com/yeyushengfan258/We10X-icon-theme
license    : GPL-3.0-or-later
component  : desktop.theme
summary    : A colorful design icon theme for all linux desktops
description: |
    A colorful design icon theme for all linux desktops!
setup      : |
    %patch -p1 < $pkgfiles/0001-fix-install.patch
install    : |
    install -dm00644 $installdir/usr/share/icons
    ./install.sh -d $installdir/usr/share/icons/
    chmod -R 00644 $installdir/usr/share/icons/*
    rm -rf $installdir/usr/share/icons/*/{AUTHORS,COPYING}
