name       : gst
version    : 0.7.5
release    : 2
source     :
    - https://gitlab.com/leinardi/gst/-/archive/0.7.5/gst-0.7.5.tar.gz : 6d78f96a7f8663ca81be34cbea7295a75da41b4a49f5cb1c6cd1d0478d60a3f5
homepage   : https://gitlab.com/leinardi/gst
license    : GPL-3.0-or-later
component  : system.utils
summary    : System utility designed to stress and monitor various hardware components
description: |
    GST (GtkStressTesting) is a GTK system utility designed to stress and monitor various hardware components like CPU and RAM.
builddeps  :
    - pkgconfig(appstream-glib)
    - pkgconfig(gtk+-3.0)
rundeps    :
    - dmidecode
    - lm_sensors
    - python-humanfriendly # Extra Repo
    - python-injector
    - python-peewee
    - python-psutil
    - python-requests
    - python-rx             # Extra Repo
    - pyyaml
    - pyxdg
    - stress-ng
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
