name       : gst
version    : 0.7.4
release    : 1
source     :
    - https://gitlab.com/leinardi/gst/-/archive/0.7.4/gst-0.7.4.tar.gz : 47f47ac4ea1d497975fe326f95f55b3d6c9e32aa00acbea0952561d1179b1562
homepage   : https://gitlab.com/leinardi/gst
license    : GPL-3.0-or-later
component  : system.utils
summary    : System utility designed to stress and monitor various hardware components
description: |
    GST (GtkStressTesting) is a GTK system utility designed to stress and monitor various hardware components like CPU and RAM.
builddeps  :
    - pkgconfig(appstream-glib)
    - pkgconfig(gtk+-3.0)
rundeps    :
    - dmidecode
    - lm_sensors
    - python-humanfriendly
    - python-injector
    - python-peewee
    - python-psutil
    - python-requests
    - python-rx
    - pyyaml
    - pyxdg
    - stress-ng
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
