name       : python-rx
version    : 3.2.0
release    : 2
source     :
    - https://github.com/ReactiveX/RxPY/archive/v3.2.0.tar.gz : 2b6cd275a3e4641d30fde88da012f470d8cea3d23b1f42aef0243c2fc199e7aa
homepage   : https://rxpy.rtfd.io
license    : MIT
component  : programming.python
summary    : Reactive extensions for Python
description: |
    A library for composing asynchronous and event-based programs using observable collections and query operator functions in Python
builddeps  :
    - pytest-runner
    - python-coverage
    - python-pytest-asyncio
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
