name       : gst
version    : 0.7.1
release    : 1
source     :
    - https://gitlab.com/leinardi/gst/-/archive/0.7.1/gst-0.7.1.tar.gz : 1f97525cdebb6ab9c8e84de26691d8cd8fa1bac733d8e672f71898afade3620b
license    : GPL-3.0-or-later
component  : system.utils
summary    : System utility designed to stress and monitor various hardware components
description: |
    GST (GtkStressTesting) is a GTK system utility designed to stress and monitor various hardware components like CPU and RAM.
builddeps  :
    - pkgconfig(appstream-glib)
    - pkgconfig(gtk+-3.0)
rundeps    :
    - dmidecode
    - lm_sensors 
    - python-humanfriendly
    - python-injector
    - python-peewee
    - python-psutil
    - python-requests
    - python-rx
    - pyyaml
    - pyxdg
    - stress-ng
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
