name       : ubuntu-budgie-extras
version    : 0.10.1
release    : 4
source     :
    - https://github.com/UbuntuBudgie/budgie-extras/releases/download/v0.10.1/budgie-extras-0.10.1.tar.xz : ab058fe660c5cea4ecc88c2afa21e86a82352979c3d4040c3733c7311b9ae0aa
homepage   : https://github.com/UbuntuBudgie/budgie-extras
license    : GPL-3.0-or-later
component  :
    - ^budgie-another-trash-applet : desktop.budgie
    - ^budgie-app-launcher-applet : desktop.budgie
    - ^budgie-brightness-controll-applet : desktop.budgie
    - ^budgie-dropby-applet : desktop.budgie
    - ^budgie-extras-daemon : desktop.budgie
    - ^budgie-fuzzyclock-applet : desktop.budgie
    - ^budgie-keyboard-autoswitch-applet : desktop.budgie
    - ^budgie-quickchar-applet : desktop.budgie
    - ^budgie-recentlyused-applet : desktop.budgie
    - ^budgie-rotation-lock-applet : desktop.budgie
    - ^budgie-showtime-applet : desktop.budgie
    - ^budgie-takeabreak-applet : desktop.budgie
    - ^budgie-wallpaper-switcher-applet : desktop.budgie
    - ^budgie-window-mover-applet : desktop.budgie
    - ^budgie-workspace-overview-applet : desktop.budgie
    - ^budgie-workspace-stopwatch-applet : desktop.budgie
summary    :
    - Budgie-extras from Ubuntu Budgie
    - ^budgie-another-trash-applet : Trash is a Budgie Desktop applet for productivity.
    - ^budgie-app-launcher-applet : App Launcher is a Budgie Desktop applet for productivity. This applet lists your favourite apps.
    - ^budgie-brightness-controll-applet : Brightness Controller is a Budgie Desktop applet for productivity.
    - ^budgie-dropby-applet : The DropBy applet pops up in the panel on the occasion of connecting a usb device
    - ^budgie-extras-daemon : This on logon process manages keyboard shortcuts delivered via .bde files for various extras-plugins
    - ^budgie-fuzzyclock-applet : Shows the time in a Fuzzy Way.
    - ^budgie-keyboard-autoswitch-applet : Keyboard Auto Switch is an applet to use a different input keyboard layout per application
    - ^budgie-quickchar-applet : Quickly find and choose the equivalent locale character for an ascii character
    - ^budgie-recentlyused-applet : Show (Gtk applications') recently used items in a menu.
    - ^budgie-rotation-lock-applet : Is an applet to an easy way to rotation lock or unlock your screen
    - ^budgie-showtime-applet : Budgie Showtime is a digital desktop clock, showing time, and optionally, date.
    - ^budgie-takeabreak-applet : Budgie TakeaBreak is a pomodoro like applet, to make sure to take regular breaks from working
    - ^budgie-wallpaper-switcher-applet : Is an application (applet) to show a different wallpaper on each of the workspaces
    - ^budgie-window-mover-applet : Budgie WindoMover is an application (applet) to quickly move windows to any of the other workspaces
    - ^budgie-workspace-overview-applet : An applet to have quick access to all windows across all workspaces
    - ^budgie-workspace-stopwatch-applet : Workspace Timer Applet is an applet to keep track of usage per workspace
description:
    - Budgie-extras from Ubuntu Budgie. Here are some applets not yet included in official Solus Repository.
    - ^budgie-another-trash-applet : Trash is a Budgie Desktop applet for productivity.
    - ^budgie-app-launcher-applet : App Launcher is a Budgie Desktop applet for productivity. This applet lists your favourite apps.
    - ^budgie-brightness-controll-applet : Brightness Controller is a Budgie Desktop applet for productivity.
    - ^budgie-dropby-applet : The DropBy applet pops up in the panel on the occasion of connecting a usb device. The applet subsequently offers the option(s) to mount, unmount/eject, and, in case of a flash drive, to make a local copy of the drive's content. The info shows the free sapace on the volume. The applet shows its icon in the panel if, and as long as, any usb drive is connected.
    - ^budgie-extras-daemon : This on logon process manages keyboard shortcuts delivered via .bde files for various extras-plugins.
    - ^budgie-fuzzyclock-applet : Shows the time in a Fuzzy Way.
    - ^budgie-keyboard-autoswitch-applet : Keyboard Auto Switch is an applet to use a different input keyboard layout per application. Simply set a default layout to be used in general. Subsequently, simply set a different layout, with the application's window in front, and an exception for that specific application is remembered. Exceptions can be removed at any time, either from the applet's menu or by setting the application's layout, again, with its window in front.
    - ^budgie-quickchar-applet : Quickly find and choose the equivalent locale character for an ascii character.
    - ^budgie-recentlyused-applet : Show (Gtk applications') recently used items in a menu.
    - ^budgie-rotation-lock-applet : Is an applet to an easy way to rotation lock or unlock your screen.
    - ^budgie-showtime-applet : Budgie Showtime is a digital desktop clock, showing time, and optionally, date. Textcolor of both can be set separately from the applet's menu.
    - ^budgie-takeabreak-applet : Budgie TakeaBreak is a pomodoro like applet, to make sure to take regular breaks from working. Options from Budgie Settings include turning the screen upside down, dim the screen, lock screen or show a countdown message on break time. The applet can be accessed quickly from the panel to temporarily switch it off.
    - ^budgie-wallpaper-switcher-applet : Is an application (applet) to show a different wallpaper on each of the workspaces. Usage is simple; add the applet to the panel and set wallpapers on each of the workspaces in the way you are used to. The applet will remember what wallpaper was set on each of the workspaces.
    - ^budgie-window-mover-applet : Budgie WindoMover is an application (applet) to quickly move windows to any of the other workspaces. Just drag a window to the bottom of the screen and a bar will popup, representing the workspaces. Click on any of the numbers (or press the corresponding number on the keyboard), and the window will move to that workspace.
    - ^budgie-workspace-overview-applet : An applet to have quick access to all windows across all workspaces
    - ^budgie-workspace-stopwatch-applet : Workspace Timer Applet is an applet to keep track of usage per workspace, e.g. to find out how much minutes/hours were actually spent on a job. Workspaces can be freely named, custom names and all data are rmembered, also after logout/restart, until the RESET button is pressed.
patterns   :
    - ^budgie-another-trash-applet :
        - /usr/lib64/budgie-desktop/plugins/budgie-trash
        - /usr/share/pixmaps/budgie-trash*
    - ^budgie-app-launcher-applet :
        - /usr/lib64/budgie-desktop/plugins/budgie-app-launcher
        - /usr/share/pixmaps/budgie-app-launcher*
    - ^budgie-brightness-controll-applet :
        - /usr/lib64/budgie-desktop/plugins/budgie-brightness-controller
        - /usr/share/pixmaps/budgie-brightness-controller-1-symbolic.svg
    - ^budgie-dropby-applet :
        - /usr/lib64/budgie-desktop/plugins/budgie-dropby
        - /usr/share/pixmaps/budgie-dropby*
    - ^budgie-extras-daemon :
        - /etc/xdg/autostart/budgie-extras-daemon.desktop
        - /usr/bin/budgie-extras-daemon
        - /usr/share/budgie-extras-daemon/example.bde
        - /usr/share/man/man1/budgie-extras-daemon.1
    - ^budgie-fuzzyclock-applet :
        - /usr/lib64/budgie-desktop/plugins/budgie-fuzzyclock
    - ^budgie-keyboard-autoswitch-applet :
        - /usr/lib64/budgie-desktop/plugins/budgie-keyboard-autoswitch
        - /usr/share/pixmaps/budgie-keyboard-autoswitch-symbolic.svg
    - ^budgie-quickchar-applet :
        - /etc/xdg/autostart/quickchar-autostart.desktop
        - /usr/bin/quickchar
        - /usr/lib64/quickchar
        - /usr/share/applications/quickchar.desktop
        - /usr/share/budgie-extras-daemon/quickchar.bde
        - /usr/share/glib-2.0/schemas/org.ubuntubudgie.quickchar.gschema.xml
        - /usr/share/man/man1/quickchar.1
        - /usr/share/quickchar/chardata
    - ^budgie-recentlyused-applet :
        - /usr/lib64/budgie-desktop/plugins/budgie-recentlyused
        - /usr/share/glib-2.0/schemas/org.ubuntubudgie.plugins.budgie-recentlyused.gschema.xml
    - ^budgie-rotation-lock-applet :
        - /usr/lib64/budgie-desktop/plugins/budgie-rotation-lock
        - /usr/share/pixmaps/budgie-rotation*
    - ^budgie-showtime-applet :
        - /usr/lib64/budgie-desktop/plugins/budgie-showtime
        - /usr/share/glib-2.0/schemas/org.ubuntubudgie.plugins.budgie-showtime.gschema.xml
        - /usr/share/pixmaps/showtimenew-symbolic.svg
    - ^budgie-takeabreak-applet :
        - /usr/lib64/budgie-desktop/plugins/budgie-takeabreak
        - /usr/share/glib-2.0/schemas/org.ubuntubudgie.plugins.takeabreak.gschema.xml
        - /usr/share/pixmaps/takeabreak*
    - ^budgie-wallpaper-switcher-applet :
        - /usr/lib64/budgie-desktop/plugins/budgie-wswitcher
        - /usr/share/pixmaps/budgie-wsw-symbolic.svg
    - ^budgie-window-mover-applet :
        - /usr/lib64/budgie-desktop/plugins/budgie-wmover
        - /usr/share/pixmaps/budgie-wmover-symbolic.svg
    - ^budgie-workspace-overview-applet :
        - /usr/lib64/budgie-desktop/plugins/budgie-wsoverview
        - /usr/share/glib-2.0/schemas/org.ubuntubudgie.plugins.budgie-wsoverview.gschema.xml
        - /usr/share/pixmaps/budgie-wsoverview-symbolic.svg
        - /usr/share/pixmaps/ws*
    - ^budgie-workspace-stopwatch-applet :
        - /usr/lib64/budgie-desktop/plugins/budgie-workspace-stopwatch
        - /usr/share/pixmaps/budgie-wstopwatch-symbolic.svg
builddeps  :
    - pkgconfig(budgie-1.0)
    - pkgconfig(gee-0.8)
    - pkgconfig(gnome-settings-daemon)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(keybinder-3.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libwnck-3.0)
    - vala
rundeps    :
    - ^budgie-another-trash-applet : budgie-extras
    - ^budgie-app-launcher-applet : budgie-extras
    - ^budgie-brightness-controll-applet : budgie-extras
    - ^budgie-dropby-applet : 
        - budgie-extras
        - python-psutil
        - python3-pyudev
    - ^budgie-extras-daemon : budgie-extras
    - ^budgie-fuzzyclock-applet : budgie-extras
    - ^budgie-keyboard-autoswitch-applet :
        - budgie-extras
        - xdotool
        - xprop
    - ^budgie-quickchar-applet :
        - budgie-extras
        - budgie-extras-daemon
        - python-xlib
        - wmctrl
    - ^budgie-recentlyused-applet : budgie-extras
    - ^budgie-rotation-lock-applet : budgie-extras
    - ^budgie-showtime-applet : budgie-extras
    - ^budgie-takeabreak-applet :
        - budgie-extras
        - xprintidle
        - wmctrl
    - ^budgie-wallpaper-switcher-applet :
        - budgie-extras
        - wmctrl
    - ^budgie-window-mover-applet :
        - budgie-extras
        - xdotool
        - xprop
    - ^budgie-workspace-overview-applet :
        - budgie-extras
        - xprop
        - wmctrl
    - ^budgie-workspace-stopwatch-applet : budgie-extras
setup      : |
    %meson_configure \
        -Dbuild-all=false \
        -Dbuild-app-launcher=true \
        -Dbuild-brightness-controller=true \
        -Dbuild-extrasdaemon=true \
        -Dbuild-dropby=true \
        -Dbuild-fuzzyclock=true \
        -Dbuild-keyboard-autoswitch=true \
        -Dbuild-quickchar=true \
        -Dbuild-recentlyused=true \
        -Dbuild-rotation-lock=true \
        -Dbuild-showtime=true \
        -Dbuild-takeabreak=true \
        -Dbuild-trash=true \
        -Dbuild-wmover=true \
        -Dbuild-wsoverview=true \
        -Dbuild-wswitcher=true \
        -Dbuild-workspacestopwatch=true
build      : |
    %ninja_build
install    : |
    %ninja_install

    #These are not needed since they are already in budgie-extras to avoid conflicts.
    rm -rf $installdir/usr/share/locale
