name       : ubuntu-budgie-extras
version    : 0.10.1
release    : 4
source     :
    - https://github.com/UbuntuBudgie/budgie-extras/releases/download/v0.10.1/budgie-extras-0.10.1.tar.xz : ab058fe660c5cea4ecc88c2afa21e86a82352979c3d4040c3733c7311b9ae0aa
homepage   : https://github.com/UbuntuBudgie/budgie-extras
license    : GPL-3.0-or-later
component  :
    - ^budgie-app-launcher-applet : desktop.budgie
    - ^budgie-dropby-applet : desktop.budgie
    - ^budgie-recentlyused-applet : desktop.budgie
    - ^budgie-showtime-applet : desktop.budgie
    - ^budgie-takeabreak-applet : desktop.budgie
    - ^budgie-trash-applet : desktop.budgie
summary    :
    - Budgie-extras from Ubuntu Budgie
    - ^budgie-app-launcher-applet : App Launcher is a Budgie Desktop applet for productivity. This applet lists your favourite apps.
    - ^budgie-dropby-applet : The DropBy applet pops up in the panel on the occasion of connecting a usb device
    - ^budgie-recentlyused-applet : Show (Gtk applications') recently used items in a menu.
    - ^budgie-showtime-applet : Budgie Showtime is a digital desktop clock, showing time, and optionally, date.
    - ^budgie-takeabreak-applet : Budgie TakeaBreak is a pomodoro like applet, to make sure to take regular breaks from working
    - ^budgie-trash-applet : Trash is a Budgie Desktop applet for productivity.
description:
    - Budgie-extras from Ubuntu Budgie. Here are some applets not yet included in official Solus Repository.
    - ^budgie-app-launcher-applet : App Launcher is a Budgie Desktop applet for productivity. This applet lists your favourite apps.
    - ^budgie-dropby-applet : The DropBy applet pops up in the panel on the occasion of connecting a usb device. The applet subsequently offers the option(s) to mount, unmount/eject, and, in case of a flash drive, to make a local copy of the drive's content. The info shows the free sapace on the volume. The applet shows its icon in the panel if, and as long as, any usb drive is connected.
    - ^budgie-recentlyused-applet : Show (Gtk applications') recently used items in a menu.
    - ^budgie-showtime-applet : Budgie Showtime is a digital desktop clock, showing time, and optionally, date. Textcolor of both can be set separately from the applet's menu.
    - ^budgie-takeabreak-applet : Budgie TakeaBreak is a pomodoro like applet, to make sure to take regular breaks from working. Options from Budgie Settings include turning the screen upside down, dim the screen, lock screen or show a countdown message on break time. The applet can be accessed quickly from the panel to temporarily switch it off.
    - ^budgie-trash-applet : Trash is a Budgie Desktop applet for productivity.
patterns   :
    - ^budgie-app-launcher-applet :
        - /usr/lib64/budgie-desktop/plugins/budgie-app-launcher
        - /usr/share/pixmaps/budgie-app-launcher*
    - ^budgie-dropby-applet :
        - /usr/lib64/budgie-desktop/plugins/budgie-dropby
        - /usr/share/pixmaps/budgie-dropby*
    - ^budgie-recentlyused-applet :
        - /usr/lib64/budgie-desktop/plugins/budgie-recentlyused
        - /usr/share/glib-2.0/schemas/org.ubuntubudgie.plugins.budgie-recentlyused.gschema.xml
    - ^budgie-showtime-applet :
        - /usr/lib64/budgie-desktop/plugins/budgie-showtime
        - /usr/share/glib-2.0/schemas/org.ubuntubudgie.plugins.budgie-showtime.gschema.xml
        - /usr/share/pixmaps/showtimenew-symbolic.svg
    - ^budgie-takeabreak-applet :
        - /usr/lib64/budgie-desktop/plugins/budgie-takeabreak
        - /usr/share/glib-2.0/schemas/org.ubuntubudgie.plugins.takeabreak.gschema.xml
        - /usr/share/pixmaps/takeabreak*
    - ^budgie-trash-applet :
        - /usr/lib64/budgie-desktop/plugins/budgie-trash
        - /usr/share/pixmaps/budgie-trash*
builddeps  :
    - pkgconfig(budgie-1.0)
    - pkgconfig(gee-0.8)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libwnck-3.0)	# showtime
    - vala
rundeps    :
    - ^budgie-app-launcher-applet : budgie-extras
    - ^budgie-dropby-applet : 
        - budgie-extras
        - python3-pyudev
    - ^budgie-recentlyused-applet : budgie-extras
    - ^budgie-showtime-applet : budgie-extras
    - ^budgie-takeabreak-applet :
        - budgie-extras
        - xprintidle
        - wmctrl
    - ^budgie-trash-applet : budgie-extras
setup      : |
    %patch -p1 < $pkgfiles/0001-enable-all-options-by-default.patch #budgie-takeabreak-applet
    %meson_configure \
        -Dbuild-all=false \
        -Dbuild-app-launcher=true \
        -Dbuild-dropby=true \
        -Dbuild-recentlyused=true \
        -Dbuild-showtime=true \
        -Dbuild-takeabreak=true \
        -Dbuild-trash=true
build      : |
    %ninja_build
install    : |
    %ninja_install

    #These are not needed since they are already in budgie-extras to avoid conflicts.
    rm -rf $installdir/usr/share/locale
