name       : parlatype-libreoffice-extension
version    : 3.1.1
release    : 1
source     :
    - https://github.com/gkarsay/parlatype-libreoffice-extension/releases/download/v3.1.1/parlatype-libreoffice-extension-3.1.1.tar.gz : 51ec1afb69c6bc0bafa28a2c2799aa75a161653cc22a8b2920c24d881437e618
homepage   : https://www.parlatype.org/
license    : GPL-3.0-or-later
component  : multimedia.audio
summary    : Parlatype LibreOffice Extension
description: |
    Parlatype LibreOffice Extension.
builddeps  :
    - pkgconfig(appstream)
rundeps    :
    - libreoffice-base
    - parlatype
setup      : |
    %meson_configure \
        -Dbundled=true \
        -Dlibreoffice-dir=%libdir%/libreoffice
build      : |
    %ninja_build
install    : |
    %ninja_install
