name       : libfm
version    : 1.3.2
release    : 1
source     :
    - https://downloads.sourceforge.net/pcmanfm/libfm-1.3.2.tar.xz : a5042630304cf8e5d8cff9d565c6bd546f228b48c960153ed366a34e87cad1e5
homepage   : https://lxde.org/
license    : GPL-2.0-or-later
component  : programming.library
summary    : Core library of PCManFM file manager
description: |
    Core library of PCManFM file manager.
builddeps  :
    - pkgconfig(libexif)
    - pkgconfig(libmenu-cache) # Extra Repo
    - pkgconfig(glib-2.0)
    - pkgconfig(gtk+-2.0)
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install

    # remove files that belong to libfm-extra
    rm -f $installdir%libdir%/libfm-extra.so*
    rm -f $installdir%libdir%/pkgconfig/libfm-extra.pc
    rm -f $installdir/usr/include/libfm/fm-{extra,version,xml-file}.h
