name       : protonvpn-gui
version    : 1.3.0
release    : 1
source     :
    - https://github.com/ProtonVPN/linux-app/archive/refs/tags/1.3.0.tar.gz : b2e9db2c167ea3c0b520fd0bdff21e127b7ac229584c1e8500aa504202478a5c
homepage   : https://protonvpn.com/
license    : GPL-3.0-or-later
component  : network.clients
summary    : Official ProtonVPN Linux app
description: |
    The ProtonVPN Linux App Library is intended for every ProtonVPN service user.
rundeps    :
    - libgtk-3
    - python-protonvpn-nm-lib # Extra Repo
    - python-psutil
build      : |
    %python3_setup
install    : |
    %python3_install

    install -Dm00644 protonvpn.desktop -t $installdir/usr/share/applications
    install -Dm00644 protonvpn_gui/assets/icons/protonvpn-logo.png -t $installdir/usr/share/icons/hicolor/scalable/apps
