name       : fluent-icon-theme
version    : 2022.09.20
release    : 2
source     :
    - https://github.com/vinceliuice/Fluent-icon-theme/archive/refs/tags/2022-09-20.tar.gz : af7df03aa7a035d488ee4ca71f02f9177e4eefdc8a6fc3ef3ab2de6158a5a558
homepage   : https://github.com/vinceliuice/Fluent-icon-theme
license    : GPL-3.0-or-later
component  : desktop.theme
summary    : Fluent icon theme for linux desktops
description: |
    Fluent icon theme for linux desktops.
setup      : |
    sed -e '/gtk-update-icon-cache/d' -i install.sh
install    : |
    install -dm00644 $installdir/usr/share/icons
    ./install.sh --all --dest $installdir/usr/share/icons
patterns   :
    - green : /usr/share/icons/*green*
    - grey : /usr/share/icons/*grey*
    - orange : /usr/share/icons/*orange*
    - pink : /usr/share/icons/*pink*
    - purple : /usr/share/icons/*purple*
    - red : /usr/share/icons/*red*
    - yellow : /usr/share/icons/*yellow*
