name       : python-wordcloud
version    : 1.8.1
release    : 1
source     :
    - https://github.com/amueller/word_cloud/archive/1.8.1.tar.gz : 55a2c20e9fe838e9b7f052d17f56b5825d7d1040f6b3af36d1817d1b611d0b42
homepage   : https://amueller.github.io/word_cloud
license    : MIT
component  : programming.python
summary    : A little word cloud generator in Python
description: |
    A little word cloud generator in Python.
builddeps  :
    - pkgconfig(python3)
    - matplotlib
    - numpy
    - python-mock
    - python-pillow
    - python-pytest-cov
rundeps    :
    - matplotlib
    - numpy
    - python-pillow
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v -k 'not test_cli_as_executable'
