name       : python-wordcloud
version    : 1.7.0
release    : 1
source     :
    - https://github.com/amueller/word_cloud/archive/1.7.0.tar.gz : 7e0f6898d41dbf4b59464fc1ce4fa2df61ce66d3fe5615058439eae8ce72e38e
homepage   : https://amueller.github.io/word_cloud
license    : MIT
component  : programming.python
summary    : A little word cloud generator in Python
description: |
    A little word cloud generator in Python
builddeps  :
    - pkgconfig(python3)
    - matplotlib         # Check
    - numpy              # Check
    - python-pillow      # Check
rundeps    :
    - python-pillow
    - matplotlib
    - numpy
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
