name       : wavemon
version    : 0.9.3
release    : 1
source     :
    - https://github.com/uoaerg/wavemon/archive/v0.9.3.tar.gz : ddbeb6ec8ed7d94fa895e5d57ecfe338495df3991f6facc7cf40aa121bf7ff60
homepage   : https://github.com/uoaerg/wavemon
license    : GPL-3.0-or-later
component  : network.util
summary    : Ncurses-based monitoring application for wireless network devices
description: |
    wavemon is a wireless device monitoring application that allows you to watch signal and noise levels, packet statistics, device configuration and network parameters of your wireless network hardware. It should work (though with varying features) with all devices supported by the Linux kernel.
builddeps  :
    - pkgconfig(libcap)
    - pkgconfig(libnfnetlink)
    - pkgconfig(libnl-genl-3.0)
    - pkgconfig(ncursesw)
setup      : |
    sed -r 's|(/share)|\1/doc|g' -i Makefile.in
    sed -r 's|\?=|=|g' -i Makefile.in
    %configure
build      : |
    %make
install    : |
    %make_install
    rm -rf $installdir/usr/share/doc
