name       : bashtop
version    : 0.9.25
release    : 1
source     :
    - https://github.com/aristocratos/bashtop/archive/v0.9.25.tar.gz : 676126df13a860df578a3a130783e0abb1c0b7628dddcfd7591069b832e8d8ad
homepage   : https://github.com/aristocratos/bashtop
license    : Apache-2.0
component  : system.utils
summary    : Linux resource monitor
description: |
    Linux resource monitor written in bash
install    : |
    install -Dm00755 bashtop $installdir/usr/bin/bashtop
