name       : bashtop
version    : 0.9.7
release    : 1
source     :
    - https://github.com/aristocratos/bashtop/archive/v0.9.7.tar.gz : 2b3775dc3e9444d32038a16691ebd8994f274dcdd322ffa031f9ac76b07b491f
homepage   : https://github.com/aristocratos/bashtop
license    : Apache-2.0
component  : system.utils
summary    : Linux resource monitor
description: |
    Linux resource monitor written in bash
install    : |
    install -Dm00755 bashtop $installdir/usr/bin/bashtop
