name       : bashtop
version    : 0.8.28
release    : 3
source     :
    - https://github.com/aristocratos/bashtop/archive/v0.8.28.tar.gz : f38bf0f36cb766e246ae432a3cf6023880e8279d2d7f3e8aa0ce5ba9e9f58542
homepage   : https://github.com/aristocratos/bashtop
license    : Apache-2.0
component  : system.utils
summary    : Linux resource monitor
description: |
    Linux resource monitor written in bash
install    : |
    install -Dm00755 bashtop $installdir/usr/bin/bashtop
