name       : font-caskaydia-cove-nerd
version    : 2.1.0
release    : 1
source     :
    - https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/CascadiaCode.zip : 92b50960305c580fc90bb3bd5456e26edc9b321907dfa2578066a9b38e2a94e0
homepage   : https://www.nerdfonts.com/
license    : MIT
component  : 
    - ttf : desktop.font
    - mono-ttf : desktop.font
summary    : Patched version of Cascadia Code
description: |
    Patched version of Cascadia Code
patterns   :
    - ttf : /usr/share/fonts/truetype/caskaydia-cove-nerd/Caskaydia Cove Nerd Font Complete.ttf
    - mono-ttf : /usr/share/fonts/truetype/caskaydia-cove-nerd/Caskaydia Cove Nerd Font Complete Mono.ttf
install    : |
    install -dm00644 $installdir/usr/share/fonts/truetype/caskaydia-cove-nerd
    install -Dm00644 "Caskaydia Cove Nerd Font Complete.ttf" -t $installdir/usr/share/fonts/truetype/caskaydia-cove-nerd/
    install -Dm00644 "Caskaydia Cove Nerd Font Complete Mono.ttf" -t $installdir/usr/share/fonts/truetype/caskaydia-cove-nerd/
