name       : bauh
version    : 0.10.7
release    : 16
source     :
    - https://github.com/vinifmor/bauh/archive/refs/tags/0.10.7.tar.gz : d3d4e7bb798cd85201a90a8756b6b53d3d5f3e11308edf2548634939113b48df
homepage   : https://github.com/vinifmor/bauh
license    : Zlib
component  : desktop
summary    : Graphical interface for application management (AppImage, Flatpak, Snap, Web)
description: |
    bauh (ba-oo), formerly known as fpakman, is a graphical interface for managing your Linux software (packages/applications). It currently supports the following formats: AppImage, Flatpak, Snap and Web applications.
checkdeps  :
    - flatpak
    - python-colorama
    - python-dateutil
    - python-requests
    - python3-qt5
rundeps    :
    - aria2
    - flatpak
    - python-colorama
    - python-dateutil
    - python-requests
    - python3-qt5
    - snapd
    #- timeshift          # Optional
    - wget
build      : |
    %python3_setup
install    : |
    %python3_install
    install -Dm00644 bauh/desktop/*.desktop -t $installdir/usr/share/applications
check      : |
    %python3_test
