name       : bandwhich
version    : 0.17.0
release    : 1
source     :
    - https://github.com/imsnif/bandwhich/archive/0.17.0.tar.gz : 9bcde0e10d0a601105d89fa808c0ee2c7880de40877619ae5350b9e2c9e4f343
homepage   : https://github.com/imsnif/bandwhich
license    : MIT
component  : network.util
summary    : Terminal bandwidth utilization tool
description: |
    This is a CLI utility for displaying current network utilization by process, connection and remote IP/hostname
networking : yes
builddeps  :
    - cargo
build      : |
    cargo build %JOBS% --release --locked
install    : |
    install -Dm00755 target/release/bandwhich $installdir/usr/bin/bandwhich
    install -Dm00644 docs/bandwhich.1 $installdir/usr/share/man/man1/bandwhich.1
