name       : bandwhich
version    : 0.20.0
release    : 1
source     :
    - https://github.com/imsnif/bandwhich/archive/0.20.0.tar.gz : 4bbf05be32439049edd50bd1e4d5a2a95b0be8d36782e4100732f0cc9f19ba12
homepage   : https://github.com/imsnif/bandwhich
license    : MIT
component  : network.util
summary    : Terminal bandwidth utilization tool
description: |
    This is a CLI utility for displaying current network utilization by process, connection and remote IP/hostname
networking : yes
builddeps  :
    - cargo
build      : |
    cargo build %JOBS% --release --locked
install    : |
    install -Dm00755 target/release/bandwhich $installdir/usr/bin/bandwhich
    install -Dm00644 docs/bandwhich.1 $installdir/usr/share/man/man1/bandwhich.1
