name       : bandwhich
version    : 0.19.0
release    : 1
source     :
    - https://github.com/imsnif/bandwhich/archive/0.19.0.tar.gz : 82ad604e2b80d4434633860dd81a1d73cd59d54bde7241f4e86c95900912befc
homepage   : https://github.com/imsnif/bandwhich
license    : MIT
component  : network.util
summary    : Terminal bandwidth utilization tool
description: |
    This is a CLI utility for displaying current network utilization by process, connection and remote IP/hostname
networking : yes
builddeps  :
    - cargo
build      : |
    cargo build %JOBS% --release --locked
install    : |
    install -Dm00755 target/release/bandwhich $installdir/usr/bin/bandwhich
    install -Dm00644 docs/bandwhich.1 $installdir/usr/share/man/man1/bandwhich.1
