name       : bandwhich
version    : 0.13.0
release    : 3
source     :
    - https://github.com/imsnif/bandwhich/archive/0.13.0.tar.gz : 42b0411c0a9df0b51fa5bedaa5f04fb001fdf46cd2d7ea9a58c98f4f6e7a15d3
homepage   : https://github.com/imsnif/bandwhich
license    : MIT
component  : network.util
summary    : Terminal bandwidth utilization tool
description: |
    This is a CLI utility for displaying current network utilization by process, connection and remote IP/hostname
networking : yes
builddeps  :
    - cargo
build      : |
    cargo build %JOBS% --release --locked
install    : |
    install -Dm00755 target/release/bandwhich $installdir/usr/bin/bandwhich
    install -Dm00644 docs/bandwhich.1 $installdir/usr/share/man/man1/bandwhich.1
