name       : fastfetch
version    : 2.2.3
release    : 5
source     :
    - https://github.com/fastfetch-cli/fastfetch/archive/refs/tags/2.2.3.tar.gz : dda15a6a73b8e6983d808d3f82567a0e8a333a3fdb53921d88a8bb2d65a38f32
homepage   : https://github.com/LinusDierheimer/fastfetch
license    : MIT
component  : system.utils
summary    : Like neofetch, but much faster because written in C
description: |
    Fastfetch is a neofetch-like tool for fetching system information and displaying them in a pretty way. It is written in pure c, with performance and customizability in mind.
builddeps  :
    - pkgconfig(ImageMagick)
    - pkgconfig(OpenCL)
    - pkgconfig(dconf)
    - pkgconfig(gio-2.0)
    - pkgconfig(libpci)
    - pkgconfig(osmesa)
    - pkgconfig(sqlite3)
    - pkgconfig(vulkan)
    - pkgconfig(libxfconf-0)
    - pkgconfig(xrandr)
    - vulkan-headers
setup      : |
    %cmake_ninja \
        -DENABLE_IMAGEMAGICK6='OFF' \
        -DENABLE_LIBCJSON='OFF' \
        -DENABLE_RPM='OFF' \
        -Wno-dev
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rfv $installdir/usr/share/licenses
