name       : fastfetch
version    : 2.4.0
release    : 6
source     :
    - https://github.com/fastfetch-cli/fastfetch/archive/refs/tags/2.4.0.tar.gz : dbde7bb445f8e13ca8e2a324e05b6cda5bc7ed5121684d4dd0105cfb583c757e
homepage   : https://github.com/LinusDierheimer/fastfetch
license    : MIT
component  : system.utils
summary    : Like neofetch, but much faster because written in C
description: |
    Fastfetch is a neofetch-like tool for fetching system information and displaying them in a pretty way. It is written in pure c, with performance and customizability in mind.
builddeps  :
    - pkgconfig(ImageMagick)
    - pkgconfig(OpenCL)
    - pkgconfig(dconf)
    - pkgconfig(gio-2.0)
    - pkgconfig(libpci)
    - pkgconfig(osmesa)
    - pkgconfig(sqlite3)
    - pkgconfig(vulkan)
    - pkgconfig(libxfconf-0)
    - pkgconfig(xrandr)
    - vulkan-headers
setup      : |
    %cmake_ninja \
        -DENABLE_IMAGEMAGICK6='OFF' \
        -DENABLE_LIBCJSON='OFF' \
        -DENABLE_RPM='OFF' \
        -Wno-dev
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rfv $installdir/usr/share/licenses
