name       : fastfetch
version    : 2.0.5
release    : 2
source     :
    - https://github.com/fastfetch-cli/fastfetch/archive/refs/tags/2.0.5.tar.gz : 8046eb856fd95d9896220238c966125fb05e451e65d8cfc7eb25483767612235
homepage   : https://github.com/LinusDierheimer/fastfetch
license    : MIT
component  : system.utils
summary    : Like neofetch, but much faster because written in C
description: |
    Fastfetch is a neofetch-like tool for fetching system information and displaying them in a pretty way. It is written in pure c, with performance and customizability in mind.
builddeps  :
    - pkgconfig(ImageMagick)
    - pkgconfig(OpenCL)
    - pkgconfig(dconf)
    - pkgconfig(gio-2.0)
    - pkgconfig(libpci)
    - pkgconfig(osmesa)
    - pkgconfig(sqlite3)
    - pkgconfig(vulkan)
    - pkgconfig(libxfconf-0)
    - pkgconfig(xrandr)
    - vulkan-headers
setup      : |
    %cmake_ninja \
        -DENABLE_IMAGEMAGICK6='OFF' \
        -DENABLE_LIBCJSON='OFF' \
        -DENABLE_RPM='OFF' \
        -Wno-dev
build      : |
    %ninja_build
install    : |
    %ninja_install
