name       : qogir-gtk-theme
version    : 2021.02.09
release    : 1
source     :
    - https://github.com/vinceliuice/Qogir-theme/archive/2021-02-09.tar.gz : 19bddfa6ad8b539f972a3f8cdea6ad8bb33a60a624082e67124fc9585ea9eb01
homepage   : https://github.com/vinceliuice/Qogir-theme
license    : GPL-3.0-or-later
component  :
    - desktop.theme
    - win : desktop.theme
    - manjaro : desktop.theme
    - manjaro-win : desktop.theme
    - ubuntu : desktop.theme
    - ubuntu-win : desktop.theme
summary    : Qogir is a flat Design theme for GTK
description: |
    Qogir is a flat Design theme based on Arc gtk theme for Budgie, Gnome and Mate.
patterns   :
    - win : /usr/share/themes/*win*
    - manjaro : /usr/share/themes/*manjaro*
    - manjaro-win : /usr/share/themes/*manjaro-win*
    - ubuntu : /usr/share/themes/*ubuntu*
    - ubuntu-win : /usr/share/themes/*ubuntu-win*
rundeps    :
    - gtk-engines
    - gtk2-engine-murrine
    - win :
        - gtk-engines
        - gtk2-engine-murrine
    - manjaro :
        - gtk-engines
        - gtk2-engine-murrine
    - manjaro-win :
        - gtk-engines
        - gtk2-engine-murrine
    - ubuntu :
        - gtk-engines
        - gtk2-engine-murrine
    - ubuntu-win :
        - gtk-engines
        - gtk2-engine-murrine
install    : |
    install -dm00644 $installdir/usr/share/themes
    ./install.sh --dest $installdir/usr/share/themes
    rm -rf $installdir/usr/share/themes/*/{unity,AUTHORS,COPYING}
